myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:article_id>/', views.detail, name='detail'),
	path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment')
]

myfirst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	#path('', include('articles.urls')),
	path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myfirst/apps/articles/models.py
import datetime
from django.utils import timezone
from django.db import models

class User(models.Model):
	user_name = models.CharField('имя пользователя', max_length=200)
	user_date = models.DateTimeField('день рождения пользователя')

	def __str__(self):
		return self.user_name

	class Meta:
		verbose_name = 'Пользователь'
		verbose_name_plural = 'Пользователи'
		
class Article(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	article_title = models.CharField('название статьи', max_length=200)
	article_text = models.TextField('текст статьи')
	article_date = models.DateTimeField('дата публикации')

	def __str__(self):
		return self.article_title

	def was_published_recently(self):
		return self.article_date >= (timezone.now() - datetime.timedelta(days=7))

	class Meta:
		verbose_name = 'Статья'
		verbose_name_plural = 'Статьи'

class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	comment_author = models.CharField('автор комментария', max_length=50)
	comment_text = models.CharField('текст комментария', max_length=200)

	def __str__(self):
		return self.comment_text

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'

myfirst/apps/articles/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from .models import Article, Comment, User
from django.urls import reverse

def index(request):
	latest_articles_list = Article.objects.order_by('-article_date')[:5]
	return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
	try:
		a = Article.objects.get(id=article_id)
	except:
		raise Http404('Статья не найдена')

	#latest_comment_list = a.comment_set.order_by(-id)[:10]	
	latest_comment_list = Comment.objects.filter(article_id=article_id).order_by('-id')


	return render(request, 'articles/detail.html', {'article': a, 'latest_comment_list':latest_comment_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get(id=article_id)
	except:
		raise Http404('Статья не найдена')

	Comment(article_id=article_id, 
						user_id=User.objects.get(user_name=request.POST['name']).id, 
						comment_author = request.POST['name'], 
						comment_text=request.POST['text']).save()

	return HttpResponseRedirect(reverse('articles:detail', args=(a.id, ) )) 

myfirst/apps/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %} {{article.article_title}} {% endblock %}

{% block content %}
<div class="jumbotron j1">
	<h1 class="article_title">{{article.article_title}}</h1>
	<p>Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile-first projects on the web.</p>
</div>
<p>{{article.article_text}}</p>
<p>{{article.article_date}}</p>

{% if latest_comment_list %}
	{% for c in latest_comment_list %}
		<div class="comments">
			<strong>{{c.comment_author}}</strong>
			<p>{{c.comment_text}}</p>
		</div>
	{% endfor %}
{% else %}
	Комментариев нет(
{% endif %}


<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
	 	<label for="usr">Имя:</label>
	  	<input type="text" required="" placeholder="Ваше имя" name="name" class="form-control" id="usr">
	</div>
	<div class="form-group">
	    <label for="comment">Комментарий:</label>
	    <textarea class="form-control" rows="5" id="comment" name="text" required="" placeholder="Ваш комментарий"></textarea>
	</div>
	
	<button class="btn btn-primary" type="submit">Оставить комментaрий</button>
</form>

{% endblock %}

myfirst/apps/articles/templates/articles/list.html
{% extends 'base.html' %}
{% block title %}Последние статьи{% endblock %}

{% block content %}

	{% if latest_articles_list %}

		{% for a in latest_articles_list %}
			<a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
		{% endfor %}

	{% else %}
		Статьи не найдены :(
	{% endif %}
{% endblock %}

myfirst/apps/articles/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title>{% block title %}Блог{% endblock %}</title>
</head>
<body>
	<div class="header">
		<nav class="navbar navbar-inverse navbar-fixed-top">
	 		<div class="container-fluid">
	    		<div class="navbar-header header-1">
			    	<a class="navbar-brand" href="#">Блог</a>
			    </div>
		    	<ul class="nav navbar-nav">
			        <li class="active"><a href="#">Домой</a></li>
			        <li><a href="#">Нуртуган Азатбекулы</a></li>
		    	</ul>
	  		</div>
		</nav>
	</div>
	
	<div class="main">
		{% block content %}{% endblock %}
	</div>

</body>
</html>